[phases.setup]
nixPkgs = ["python3", "gcc", "nodejs_20", "npm-10_x"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.build]
cmds = ["cd frontend && npm install && npm run build"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"
